<?php

use Illuminate\Database\Seeder;

class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('articles')->insert([
    		[
    			'name' => 'Откатные ворота',
    			'product_id' => 1,
    			'cost' => 30000,
    			'price' => 35000,
    			'company_id' => 1, 
                'manufacturer_id' => 1,
    			'author_id' => 4, 
    		],
    		[
    			'name' => 'Секционные ворота',
    			'product_id' => 2,
    			'cost' => 24000,
    			'price' => null,
    			'company_id' => 1, 
                'manufacturer_id' => null,
    			'author_id' => 4, 
    		],
    		[
    			'name' => 'Забор',
    			'product_id' => 3,
    			'cost' => null,
    			'price' => null,
    			'company_id' => 1, 
                'manufacturer_id' => null,
    			'author_id' => 4, 
    		],
            [
                'name' => 'Профлист С8',
                'product_id' => 4,
                'cost' => null,
                'price' => null,
                'company_id' => 1, 
                'manufacturer_id' => null,
                'author_id' => 4, 
            ],
            [
                'name' => 'Профлист С10',
                'product_id' => 4,
                'cost' => null,
                'price' => null,
                'company_id' => 1, 
                'manufacturer_id' => null,
                'author_id' => 4, 
            ],
            [
                'name' => 'Профлист С12',
                'product_id' => 4,
                'cost' => null,
                'price' => null,
                'company_id' => 1, 
                'manufacturer_id' => null,
                'author_id' => 4, 
            ],
    		// [
    		// 	'name' => 'Труба',
    		// 	'product_id' => 4,
    		// 	'cost' => 1000,
    		// 	'price' => null,
    		// 	'company_id' => 1, 
    		// 	'author_id' => 4, 
    		// ],
    		// [
    		// 	'name' => 'Прутик',
    		// 	'product_id' => 5,
    		// 	'cost' => 100,
    		// 	'price' => null,
    		// 	'company_id' => 1, 
    		// 	'author_id' => 4, 
    		// ],
    		// [
    		// 	'name' => 'Полуфабрик',
    		// 	'product_id' => 6,
    		// 	'cost' => 5000,
    		// 	'price' => 7000,
    		// 	'company_id' => 1, 
    		// 	'author_id' => 4, 
    		// ],

            // Шторка
            // [
            //     'name' => 'Блекаут ВЕНЗЕЛЬ розовый',
            //     'product_id' => 7,
            //     'cost' => null,
            //     'price' => 700,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут ВЕНЗЕЛЬ терракотовый',
            //     'product_id' => 8,
            //     'cost' => null,
            //     'price' => 700,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут БАБОЧКИ',
            //     'product_id' => 9,
            //     'cost' => null,
            //     'price' => 480,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут ЛИСТЬЯ',
            //     'product_id' => 10,
            //     'cost' => null,
            //     'price' => 590,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут INTERIO',
            //     'product_id' => 11,
            //     'cost' => null,
            //     'price' => 670,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут Люстра',
            //     'product_id' => 12,
            //     'cost' => null,
            //     'price' => 750,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Дебют Цветы',
            //     'product_id' => 13,
            //     'cost' => null,
            //     'price' => 250,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард BYRA LUX',
            //     'product_id' => 14,
            //     'cost' => null,
            //     'price' => 753,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард POINT',
            //     'product_id' => 15,
            //     'cost' => null,
            //     'price' => 900,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард VALENTINA',
            //     'product_id' => 16,
            //     'cost' => null,
            //     'price' => 1000,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Диана',
            //     'product_id' => 17,
            //     'cost' => null,
            //     'price' => 320,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Зебра',
            //     'product_id' => 18,
            //     'cost' => null,
            //     'price' => 390,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Кудри',
            //     'product_id' => 19,
            //     'cost' => null,
            //     'price' => 560,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард ZARA',
            //     'product_id' => 20,
            //     'cost' => null,
            //     'price' => 6690,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард MOSTAR',
            //     'product_id' => 21,
            //     'cost' => null,
            //     'price' => 340,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Полоска',
            //     'product_id' => 22,
            //     'cost' => null,
            //     'price' => 460,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард  Шенил',
            //     'product_id' => 23,
            //     'cost' => null,
            //     'price' => 590,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Анита',
            //     'product_id' => 24,
            //     'cost' => null,
            //     'price' => 460,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард 7700',
            //     'product_id' => 25,
            //     'cost' => null,
            //     'price' => 740,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Жаккард Классика',
            //     'product_id' => 26,
            //     'cost' => null,
            //     'price' => 330,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Тафта Вензель',
            //     'product_id' => 27,
            //     'cost' => null,
            //     'price' => 600,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Тафта Кружева',
            //     'product_id' => 28,
            //     'cost' => null,
            //     'price' => 600,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Канвас однотонный',
            //     'product_id' => 29,
            //     'cost' => null,
            //     'price' => 750,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Бархат ADELYA',
            //     'product_id' => 30,
            //     'cost' => null,
            //     'price' => 830,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Софт двусторонний',
            //     'product_id' => 31,
            //     'cost' => null,
            //     'price' => 770,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен Interio',
            //     'product_id' => 32,
            //     'cost' => null,
            //     'price' => 680,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен МИСКЕТ',
            //     'product_id' => 33,
            //     'cost' => null,
            //     'price' => 680,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен РОМБ',
            //     'product_id' => 34,
            //     'cost' => null,
            //     'price' => 520,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен ЦВЕТЫ',
            //     'product_id' => 35,
            //     'cost' => null,
            //     'price' => 560,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен SANPA',
            //     'product_id' => 36,
            //     'cost' => null,
            //     'price' => 560,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен с термопечатью',
            //     'product_id' => 37,
            //     'cost' => null,
            //     'price' => 490,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен ЛИСТ Ламелла',
            //     'product_id' => 38,
            //     'cost' => null,
            //     'price' => 530,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Лен ПОЛОСКА',
            //     'product_id' => 39,
            //     'cost' => null,
            //     'price' => 580,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут однотонный Бирюза',
            //     'product_id' => 40,
            //     'cost' => null,
            //     'price' => 620,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],
            // [
            //     'name' => 'Блекаут однотонный Болотный',
            //     'product_id' => 41,
            //     'cost' => null,
            //     'price' => 620,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            // ],

    	]);
    }
}
