<?php

use Illuminate\Database\Seeder;

use App\Entity;
use App\Page;

class EntitiesTableSeeder extends Seeder
{

    public function run()
    {

        $pages = Page::where('site_id', 1)->get(['id', 'alias']);

        // Первый уровень
        Entity::insert([
            [
                'name' => 'Компании',
                'alias' => 'companies',
                'model' => 'App\Company',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'companies',
                'page_id' => $pages->firstWhere('alias', 'companies')->id,
            ],
            [
                'name' => 'Сущности',
                'alias' => 'entities',
                'model' => 'App\Entity',
                'rights' => false,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'entities',
                'page_id' => $pages->firstWhere('alias', 'entities')->id,
            ],
            [
                'name' => 'Роли',
                'alias' => 'roles',
                'model' => 'App\Role',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'roles',
                'page_id' => $pages->firstWhere('alias', 'roles')->id,
            ],


            [
                'name' => 'Сайты',
                'alias' => 'sites',
                'model' => 'App\Site',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'sites',
                'page_id' => $pages->firstWhere('alias', 'sites')->id,
            ],

            [
                'name' => 'Категории навигаци',
                'alias' => 'navigations_categories',
                'model' => 'App\NavigationsCategory',
                'rights' => false,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => null,
                'page_id' => null,
            ],

            [
                'name' => 'Категории альбомов',
                'alias' => 'albums_categories',
                'model' => 'App\AlbumsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'albums_categories',
                'page_id' => $pages->firstWhere('alias', 'albums_categories')->id,
            ],
            [
                'name' => 'Должности',
                'alias' => 'positions',
                'model' => 'App\Position',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'positions',
                'page_id' => $pages->firstWhere('alias', 'positions')->id,
            ],
            [
                'name' => 'Списки',
                'alias' => 'booklists',
                'model' => 'App\Booklist',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'booklists',
                'page_id' => $pages->firstWhere('alias', 'booklists')->id,
            ],
            [
                'name' => 'Секторы',
                'alias' => 'sectors',
                'model' => 'App\Sector',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'sectors',
                'page_id' => $pages->firstWhere('alias', 'sectors')->id,
            ],
            [
                'name' => 'Категории товаров',
                'alias' => 'goods_categories',
                'model' => 'App\GoodsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/goods_categories',
                'page_id' => $pages->firstWhere('alias', 'goods_categories')->id,
            ],
            [
                'name' => 'Категории сырья',
                'alias' => 'raws_categories',
                'model' => 'App\RawsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/raws_categories',
                'page_id' => $pages->firstWhere('alias', 'raws_categories')->id,
            ],
            [
                'name' => 'Категории упаковок',
                'alias' => 'containers_categories',
                'model' => 'App\ContainersCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/containers_categories',
                'page_id' => $pages->firstWhere('alias', 'containers_categories')->id,
            ],
            [
                'name' => 'Категории вложений',
                'alias' => 'attachments_categories',
                'model' => 'App\AttachmentsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/attachments_categories',
                'page_id' => $pages->firstWhere('alias', 'attachments_categories')->id,
            ],
            [
                'name' => 'Категории инструментов',
                'alias' => 'tools_categories',
                'model' => 'App\ToolsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/tools_categories',
                'page_id' => $pages->firstWhere('alias', 'tools_categories')->id,
            ],
            [
                'name' => 'Категории помещений',
                'alias' => 'rooms_categories',
                'model' => 'App\RoomsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/rooms_categories',
                'page_id' => $pages->firstWhere('alias', 'rooms_categories')->id,
            ],
            [
                'name' => 'Категории расходных материалов',
                'alias' => 'expendables_categories',
                'model' => 'App\ExpendablesCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/articles_categories/expendables_categories',
                'page_id' => null,
            ],
            [
                'name' => 'Категории услуг',
                'alias' => 'services_categories',
                'model' => 'App\ServicesCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/processes_categories/services_categories',
                'page_id' => $pages->firstWhere('alias', 'services_categories')->id,
            ],
            [
                'name' => 'Категории рабочих процессов',
                'alias' => 'workflows_categories',
                'model' => 'App\WorkflowsCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 1,
                'view_path' => 'products/processes_categories/workflows_categories',
                'page_id' => $pages->firstWhere('alias', 'workflows_categories')->id,
            ],
            [
                'name' => 'Страны',
                'alias' => 'countries',
                'model' => 'App\Country',
                'rights' => false,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => null,
                'page_id' => null,
            ],

            [
                'name' => 'Населенные пункты',
                'alias' => 'cities',
                'model' => 'App\City',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'cities',
                'page_id' => $pages->firstWhere('alias', 'cities')->id,
            ],
            [
                'name' => 'Расписания',
                'alias' => 'schedules',
                'model' => 'App\Schedule',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'schedules',
                'page_id' => null,
            ],
            [
                'name' => 'Метрики',
                'alias' => 'metrics',
                'model' => 'App\Metric',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'metrics',
                'page_id' => null,
            ],
            [
                'name' => 'Лиды',
                'alias' => 'leads',
                'model' => 'App\Lead',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'leads',
                'page_id' => $pages->firstWhere('alias', 'leads')->id,
            ],
            [
                'name' => 'Каталоги товаров',
                'alias' => 'catalogs_goods',
                'model' => 'App\CatalogsGoods',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'metric' => 0,
                'view_path' => 'catalogs_goods',
                'page_id' => $pages->firstWhere('alias', 'catalogs_goods')->id,
            ],
            [
                'name' => 'Каталоги услуг',
                'alias' => 'catalogs_services',
                'model' => 'App\CatalogsService',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'metric' => 0,
                'view_path' => 'catalogs_services',
                'page_id' => $pages->firstWhere('alias', 'catalogs_services')->id,
            ],
            [
                'name' => 'Рубрикаторы',
                'alias' => 'rubricators',
                'model' => 'App\Rubricator',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'metric' => 0,
                'view_path' => 'rubricators',
                'page_id' => $pages->firstWhere('alias', 'rubricators')->id,
            ],
            [
                'name' => 'Этапы',
                'alias' => 'stages',
                'model' => 'App\Stage',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'stages',
                'page_id' => $pages->firstWhere('alias', 'stages')->id,
            ],
            [
                'name' => 'Внутренние комментарии',
                'alias' => 'notes',
                'model' => 'App\Note',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'notes',
                'page_id' => null,
            ],
            [
                'name' => 'Задачи',
                'alias' => 'challenges',
                'model' => 'App\Challenge',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'challenges',
                'page_id' => $pages->firstWhere('alias', 'challenges')->id,
            ],
            [
                'name' => 'Рекламации',
                'alias' => 'claims',
                'model' => 'App\Claim',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'claims',
                'page_id' => $pages->firstWhere('alias', 'claims')->id,
            ],
            [
                'name' => 'Исходящие заказы',
                'alias' => 'orders',
                'model' => 'App\Order',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'orders',
                'page_id' => $pages->firstWhere('alias', 'orders')->id,
            ],
            [
                'name' => 'Отзывы',
                'alias' => 'feedbacks',
                'model' => 'App\Feedback',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'feedbacks',
                'page_id' => $pages->firstWhere('alias', 'feedbacks')->id,
            ],
            [
                'name' => 'Аккаунты',
                'alias' => 'accounts',
                'model' => 'App\Account',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'accounts',
                'page_id' => $pages->firstWhere('alias', 'accounts')->id,
            ],
            [
                'name' => 'Правила',
                'alias' => 'rules',
                'model' => 'App\Rule',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'rules',
                'page_id' => null,
            ],
            [
                'name' => 'Склады',
                'alias' => 'stocks',
                'model' => 'App\Stock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'stocks',
                'page_id' => $pages->firstWhere('alias', 'stocks')->id,
            ],
            [
                'name' => 'Заявки поставщикам',
                'alias' => 'applications',
                'model' => 'App\Application',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'applications',
                'page_id' => $pages->firstWhere('alias', 'applications')->id,
            ],

            [
                'name' => 'Товарные накладные',
                'alias' => 'consignments',
                'model' => 'App\Models\System\Documents\Consignment',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system.pages.documents.consignments',
                'page_id' => $pages->firstWhere('alias', 'consignments')->id,
            ],
            [
                'name' => 'Наряды на производство',
                'alias' => 'productions',
                'model' => 'App\Models\System\Documents\Production',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system.pages.documents.productions',
                'page_id' => $pages->firstWhere('alias', 'productions')->id,
            ],

            [
                'name' => 'Показатели',
                'alias' => 'indicators',
                'model' => 'App\Indicator',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'indicators',
                'page_id' => $pages->firstWhere('alias', 'indicators')->id,
            ],
            [
                'name' => 'Настройка фоток',
                'alias' => 'photo_settings',
                'model' => 'App\PhotoSetting',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'photo_settings',
                'page_id' => null,
            ],
            [
                'name' => 'Сметы',
                'alias' => 'estimates',
                'model' => 'App\Estimate',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'estimates',
                'page_id' => $pages->firstWhere('alias', 'estimates')->id,
            ],
            [
                'name' => 'Группы артикулов',
                'alias' => 'articles_groups',
                'model' => 'App\ArticlesGroup',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'articles_groups',
                'page_id' => $pages->firstWhere('alias', 'articles_groups')->id,
            ],
            [
                'name' => 'Группы процессов',
                'alias' => 'processes_groups',
                'model' => 'App\ProcessesGroup',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'processes_groups',
                'page_id' => $pages->firstWhere('alias', 'processes_groups')->id,
            ],

            [
                'name' => 'Продвижения',
                'alias' => 'promotions',
                'model' => 'App\Promotion',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'promotions',
                'page_id' => $pages->firstWhere('alias', 'promotions')->id,
            ],

            [
                'name' => 'Рассылки',
                'alias' => 'dispatches',
                'model' => 'App\Dispatch',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'dispatches',
                'page_id' => $pages->firstWhere('alias', 'dispatches')->id,
            ],

            [
                'name' => 'Домены',
                'alias' => 'domains',
                'model' => 'App\Domain',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'domains',
                'page_id' => $pages->firstWhere('alias', 'domains')->id,
            ],

            [
                'name' => 'Источники трафика',
                'alias' => 'sources',
                'model' => 'App\Source',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'sources',
                'page_id' => $pages->firstWhere('alias', 'sources')->id,
            ],

            [
                'name' => 'Настройки',
                'alias' => 'settings',
                'model' => 'App\Setting',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system/pages/settings',
                'page_id' => $pages->firstWhere('alias', 'settings')->id,
            ],

            [
                'name' => 'Портфолио',
                'alias' => 'portfolios',
                'model' => 'App\Portfolio',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system.pages.portfolios',
                'page_id' => $pages->firstWhere('alias', 'portfolios')->id,
            ],

            [
                'name' => 'Категории выполненных работ',
                'alias' => 'outcomes_categories',
                'model' => 'App\OutcomesCategory',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system.pages.outcomes_categories',
                'page_id' => $pages->firstWhere('alias', 'outcomes_categories')->id,
            ],

            [
                'name' => 'Скидки',
                'alias' => 'discounts',
                'model' => 'App\Discount',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'metric' => 0,
                'view_path' => 'system.pages.discounts',
                'page_id' => $pages->firstWhere('alias', 'discounts')->id,
            ],

            // TODO - 04.06.19 - Чистка сущностей
            // [
            //     'name' => 'Правила',
            //     'alias' => 'rights',
            //     'model' => 'Right',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'rights',
            //     'page_id' => $pages->firstWhere('alias', 'rights')->id,
            // ],
            // [
            //     'name' => 'Области',
            //     'alias' => 'regions',
            //     'model' => 'Region',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'regions',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Районы',
            //     'alias' => 'areas',
            //     'model' => 'Area',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'areas',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Категории правил',
            //     'alias' => 'category_right',
            //     'model' => 'Category_right',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'category_right',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Категории единицы измерения',
            //     'alias' => 'units_categories',
            //     'model' => 'UnitsCategory',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'units_categories',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Единицы измерения',
            //     'alias' => 'units',
            //     'model' => 'Unit',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'ancestor_id' => Entity::whereAlias('units_categories')->first(['id'])->id,
            //     'view_path' => 'units',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Локации',
            //     'alias' => 'locations',
            //     'model' => 'Location',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'locations',
            //     'page_id' => null,
            // ],

            // [
            //     'name' => 'Значения',
            //     'alias' => 'values',
            //     'model' => 'Value',
            //     'rights' => false,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'values',
            //     'page_id' => null,
            // ],
            // [
            //     'name' => 'Операционные расходы',
            //     'alias' => 'expenses',
            //     'model' => 'Expense',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'expenses',
            //     'page_id' => $pages->firstWhere('alias', 'expenses')->id,
            // ],
            // [
            //     'name' => 'Зарплаты',
            //     'alias' => 'salaries',
            //     'model' => 'Salary',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'salaries',
            //     'page_id' => $pages->firstWhere('alias', 'salaries')->id,
            // ],
            // [
            //     'name' => 'Рекламные кампании',
            //     'alias' => 'campaigns',
            //     'model' => 'Campaign',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'campaigns',
            //     'page_id' => $pages->firstWhere('alias', 'campaigns')->id,
            // ],
            // [
            //     'name' => 'Социальные сети',
            //     'alias' => 'social_networks',
            //     'model' => 'SocialNetwork',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'social_networks',
            //     'page_id' => $pages->firstWhere('alias', 'social_networks')->id,
            // ],
            // [
            //     'name' => 'Посты',
            //     'alias' => 'posts',
            //     'model' => 'Post',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'posts',
            //     'page_id' => $pages->firstWhere('alias', 'posts')->id,
            // ],
            // [
            //     'name' => 'Поля',
            //     'alias' => 'fields',
            //     'model' => 'Field',
            //     'rights' => true,
            //     'system' => true,
            //     'author_id' => 1,
            //     'site' => 0,
            //     'view_path' => 'fields',
            //     'page_id' => $pages->firstWhere('alias', 'fields')->id,
            // ],
        ]);

        // Второй уровень
        Entity::insert([
            [
                'name' => 'Поставщики',
                'alias' => 'suppliers',
                'model' => 'App\Supplier',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'suppliers',
                'page_id' => $pages->firstWhere('alias', 'suppliers')->id,
            ],
            [
                'name' => 'Клиенты',
                'alias' => 'clients',
                'model' => 'App\Client',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'clients',
                'page_id' => $pages->firstWhere('alias', 'clients')->id,
            ],
            [
                'name' => 'Дилеры',
                'alias' => 'dealers',
                'model' => 'App\Dealer',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'dealers',
                'page_id' => $pages->firstWhere('alias', 'dealers')->id,
            ],
            [
                'name' => 'Производители',
                'alias' => 'manufacturers',
                'model' => 'App\Manufacturer',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'manufacturers',
                'page_id' => $pages->firstWhere('alias', 'manufacturers')->id,
            ],
            [
                'name' => 'Вендоры',
                'alias' => 'vendors',
                'model' => 'App\Vendor',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'vendors',
                'page_id' => $pages->firstWhere('alias', 'vendors')->id,
            ],


            [
                'name' => 'Отделы',
                'alias' => 'departments',
                'model' => 'App\Department',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'departments',
                'page_id' => $pages->firstWhere('alias', 'departments')->id,
            ],
            [
                'name' => 'Штат',
                'alias' => 'staff',
                'model' => 'App\Staffer',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('companies')->first(['id'])->id,
                'view_path' => 'staff',
                'page_id' => $pages->firstWhere('alias', 'staff')->id,
            ],
            [
                'name' => 'Страницы',
                'alias' => 'pages',
                'model' => 'App\Page',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'ancestor_id' => Entity::whereAlias('sites')->first(['id'])->id,
                'view_path' => 'pages',
                'page_id' => $pages->firstWhere('alias', 'pages')->id,
            ],
            [
                'name' => 'Навигации',
                'alias' => 'navigations',
                'model' => 'App\Navigation',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'ancestor_id' => Entity::whereAlias('sites')->first(['id'])->id,
                'view_path' => 'navigations',
                'page_id' => $pages->firstWhere('alias', 'navigations')->id,
            ],
            [
                'name' => 'Пользователи',
                'alias' => 'users',
                'model' => 'App\User',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'ancestor_id' => Entity::whereAlias('sites')->first(['id'])->id,
                'view_path' => 'users',
                'page_id' => $pages->firstWhere('alias', 'users')->id,
            ],

            [
                'name' => 'Альбомы',
                'alias' => 'albums',
                'model' => 'App\Album',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('albums_categories')->first(['id'])->id,
                'view_path' => 'albums',
                'page_id' => $pages->firstWhere('alias', 'albums')->id,
            ],
            [
                'name' => 'Товары',
                'alias' => 'goods',
                'model' => 'App\Goods',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('goods_categories')->first(['id'])->id,
                'view_path' => 'products/articles/goods',
                'page_id' => $pages->firstWhere('alias', 'goods')->id,
            ],
            [
                'name' => 'Сырьё',
                'alias' => 'raws',
                'model' => 'App\Raw',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('raws_categories')->first(['id'])->id,
                'view_path' => 'products/articles/raws',
                'page_id' => $pages->firstWhere('alias', 'raws')->id,
            ],
            [
                'name' => 'Упаковка',
                'alias' => 'containers',
                'model' => 'App\Container',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('containers_categories')->first(['id'])->id,
                'view_path' => 'products/articles/containers',
                'page_id' => $pages->firstWhere('alias', 'containers')->id,
            ],
            [
                'name' => 'Вложение',
                'alias' => 'attachments',
                'model' => 'App\Attachment',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('attachments_categories')->first(['id'])->id,
                'view_path' => 'products/articles/attachments',
                'page_id' => $pages->firstWhere('alias', 'attachments')->id,
            ],
            [
                'name' => 'Инструменты',
                'alias' => 'tools',
                'model' => 'App\Tool',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('tools_categories')->first(['id'])->id,
                'view_path' => 'products/articles/tools',
                'page_id' => $pages->firstWhere('alias', 'tools')->id,
            ],
            [
                'name' => 'Помещения',
                'alias' => 'rooms',
                'model' => 'App\Room',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('rooms_categories')->first(['id'])->id,
                'view_path' => 'products/articles/rooms',
                'page_id' => $pages->firstWhere('alias', 'rooms')->id,
            ],
            [
                'name' => 'Услуги',
                'alias' => 'services',
                'model' => 'App\Service',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('services_categories')->first(['id'])->id,
                'view_path' => 'products/processes/services',
                'page_id' => $pages->firstWhere('alias', 'services')->id,
            ],
            [
                'name' => 'Рабочие процессы',
                'alias' => 'workflows',
                'model' => 'App\Workflow',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('workflows_categories')->first(['id'])->id,
                'view_path' => 'products/processes/workflows',
                'page_id' => $pages->firstWhere('alias', 'workflows')->id,
            ],

            [
                'name' => 'Пункты каталогов товаров',
                'alias' => 'catalogs_goods_items',
                'model' => 'App\CatalogsGoodsItem',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('catalogs_goods')->first(['id'])->id,
                'view_path' => 'catalogs_goods_items',
                'page_id' => null,
            ],
            [
                'name' => 'Пункты каталогов услуг',
                'alias' => 'catalogs_services_items',
                'model' => 'App\CatalogsServicesItem',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('catalogs_services')->first(['id'])->id,
                'view_path' => 'catalogs_services_items',
                'page_id' => null,
            ],
            [
                'name' => 'Рубрики',
                'alias' => 'rubricators_items',
                'model' => 'App\RubricatorsItem',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('rubricators')->first(['id'])->id,
                'view_path' => 'rubricators_items',
                'page_id' => null,
            ],
            [
                'name' => 'Прайс услуги',
                'alias' => 'prices_services',
                'model' => 'App\PricesService',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('catalogs_services')->first(['id'])->id,
                'view_path' => 'prices_services',
                'page_id' => $pages->firstWhere('alias', 'prices_services')->id,
            ],
            [
                'name' => 'Прайс товара',
                'alias' => 'prices_goods',
                'model' => 'App\PricesGoods',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('catalogs_goods')->first(['id'])->id,
                'view_path' => 'prices_goods',
                'page_id' => $pages->firstWhere('alias', 'prices_goods')->id,
            ],
            [
                'name' => 'Артикулы',
                'alias' => 'articles',
                'model' => 'App\Article',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('articles_groups')->first(['id'])->id,
                'view_path' => 'articles',
                'page_id' => null,
            ],
            [
                'name' => 'Процессы',
                'alias' => 'processes',
                'model' => 'App\Process',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('processes_groups')->first(['id'])->id,
                'view_path' => 'processes',
                'page_id' => null,
            ],

            [
                'name' => 'Разделы портфолио',
                'alias' => 'portfolios_items',
                'model' => 'App\PortfoliosItem',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('portfolios')->first(['id'])->id,
                'view_path' => 'system.pages.portfolios_items',
                'page_id' => $pages->firstWhere('alias', 'portfolios_items')->id,
            ],

            [
                'name' => 'Выполненные работы',
                'alias' => 'outcomes',
                'model' => 'App\Outcome',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('outcomes_categories')->first(['id'])->id,
                'view_path' => 'system.pages.outcomes',
                'page_id' => $pages->firstWhere('alias', 'outcomes')->id,
            ],
        ]);

        // Третий
        Entity::insert([
            [
                'name' => 'Меню',
                'alias' => 'menus',
                'model' => 'App\Menu',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('navigations')->first(['id'])->id,
                'view_path' => 'menus',
                'page_id' => $pages->firstWhere('alias', 'menus')->id,
            ],
            [
                'name' => 'Фотографии',
                'alias' => 'photos',
                'model' => 'App\Photo',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('albums')->first(['id'])->id,
                'view_path' => 'photos',
                'page_id' => $pages->firstWhere('alias', 'photos')->id,
            ],
            [
                'name' => 'Сотрудники',
                'alias' => 'employees',
                'model' => 'App\Employee',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('staff')->first(['id'])->id,
                'view_path' => 'employees',
                'page_id' => $pages->firstWhere('alias', 'employees')->id,
            ],
            [
                'name' => 'Новости',
                'alias' => 'news',
                'model' => 'App\News',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 1,
                'ancestor_id' => Entity::whereAlias('rubricators_items')->first(['id'])->id,
                'view_path' => 'news',
                'page_id' => $pages->firstWhere('alias', 'news')->id,
            ],
            [
                'name' => 'Банковские счета',
                'alias' => 'bank_accounts',
                'model' => 'App\BankAccount',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('rubricators_items')->first(['id'])->id,
                'view_path' => 'bank_accounts',
                'page_id' => null,
            ],

            [
                'name' => 'Склад сырья',
                'alias' => 'raws_stocks',
                'model' => 'App\Models\System\Stocks\RawsStock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('raws')->first(['id'])->id,
                'view_path' => 'system.pages.cmv_stocks.raws_stocks',
                'page_id' => $pages->firstWhere('alias', 'raws_stocks')->id,
            ],
            [
                'name' => 'Склад упаковок',
                'alias' => 'containers_stocks',
                'model' => 'App\Models\System\Stocks\ContainersStock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('containers')->first(['id'])->id,
                'view_path' => 'system.pages.cmv_stocks.containers_stocks',
                'page_id' => $pages->firstWhere('alias', 'containers_stocks')->id,
            ],
            [
                'name' => 'Склад вложений',
                'alias' => 'attachments_stocks',
                'model' => 'App\Models\System\Stocks\AttachmentsStock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('attachments')->first(['id'])->id,
                'view_path' => 'system.pages.cmv_stocks.attachments_stocks',
                'page_id' => $pages->firstWhere('alias', 'attachments_stocks')->id,
            ],
            [
                'name' => 'Склад товаров',
                'alias' => 'goods_stocks',
                'model' => 'App\Models\System\Stocks\GoodsStock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('goods')->first(['id'])->id,
                'view_path' => 'system.pages.cmv_stocks.goods_stocks',
                'page_id' => $pages->firstWhere('alias', 'goods_stocks')->id,
            ],
            [
                'name' => 'Склад инструментов',
                'alias' => 'tools_stocks',
                'model' => 'App\Models\System\Stocks\ToolsStock',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('tools')->first(['id'])->id,
                'view_path' => 'system.pages.cmv_stocks.goods_stocks',
                'page_id' => $pages->firstWhere('alias', 'tools_stocks')->id,
            ],
            [
                'name' => 'Кейсы',
                'alias' => 'business_cases',
                'model' => 'App\BusinessCase',
                'rights' => true,
                'system' => true,
                'author_id' => 1,
                'site' => 0,
                'ancestor_id' => Entity::whereAlias('portfolios_items')->first(['id'])->id,
                'view_path' => 'system.pages.business_cases',
                'page_id' => $pages->firstWhere('alias', 'business_cases')->id,
            ],

        ]);

        // Обновляем тмц
        // Entity::where('alias', 'raws')->update(['tmc' => 1]);
        // Entity::where('alias', 'goods')->update([
        //     'tmc' => 1,
        //     'consist_id' => Entity::where('alias', 'raws')->first(['id'])->id
        // ]);

    }
}
