<?php

use Illuminate\Database\Seeder;

class FirstNamesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('first_names')->insert([
         [
          'name' => 'Александр',
          'patronymic_male' => 'Александрович',
                'patronymic_female' => 'Александровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Сергей',
          'patronymic_male' => 'Сергеевич',
                'patronymic_female' => 'Сергеевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Владимир',
          'patronymic_male' => 'Владимирович',
                'patronymic_female' => 'Владимировна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Елена',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Татьяна',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Андрей',
          'patronymic_male' => 'Андреевич',
                'patronymic_female' => 'Андреевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Алексей',
          'patronymic_male' => 'Алексеевич',
                'patronymic_female' => 'Алексеевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Ольга',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Николай',
          'patronymic_male' => 'Николаевич',
                'patronymic_female' => 'Николаевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Наталья',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Анна',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Дмитрий',
          'patronymic_male' => 'Дмитриевич',
                'patronymic_female' => 'Дмитриевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Иван',
          'patronymic_male' => 'Иванович',
                'patronymic_female' => 'Ивановна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Ирина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Мария',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Светлана',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Михаил',
          'patronymic_male' => 'Михайлович',
                'patronymic_female' => 'Михайловна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Екатерина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Евгений',
          'patronymic_male' => 'Евгеньевич',
                'patronymic_female' => 'Евгеньевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Виктор',
          'patronymic_male' => 'Викторович',
                'patronymic_female' => 'Викторовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Анастасия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Юрий',
          'patronymic_male' => 'Юрьевич',
                'patronymic_female' => 'Юрьевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Юлия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Валентина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Игорь',
          'patronymic_male' => 'Игоревич',
                'patronymic_female' => 'Игоревна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Людмила',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Галина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Василий',
          'patronymic_male' => 'Васильевич',
                'patronymic_female' => 'Васильевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Олег',
          'patronymic_male' => 'Олегович',
                'patronymic_female' => 'Олеговна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Анатолий',
          'patronymic_male' => 'Анатольевич',
                'patronymic_female' => 'Анатольевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Надежда',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Марина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Павел',
          'patronymic_male' => 'Павлович',
                'patronymic_female' => 'Павловна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Максим',
          'patronymic_male' => 'Максимович',
                'patronymic_female' => 'Максимовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Александра',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Нина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Виталий',
          'patronymic_male' => 'Витальевич',
                'patronymic_female' => 'Витальевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Валерий',
          'patronymic_male' => 'Валерьевич',
                'patronymic_female' => 'Валерьевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Любовь',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Виктория',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Роман',
          'patronymic_male' => 'Романович',
                'patronymic_female' => 'Романовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Оксана',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Денис',
          'patronymic_male' => 'Денисович',
                'patronymic_female' => 'Денисовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Дарья',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Константин',
          'patronymic_male' => 'Константинович',
                'patronymic_female' => 'Константиновна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Вячеслав',
          'patronymic_male' => 'Вячеславович',
                'patronymic_female' => 'Вячеславовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Вера',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Евгения',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Петр',
          'patronymic_male' => 'Петрович',
                'patronymic_female' => 'Петровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Антон',
          'patronymic_male' => 'Антонович',
                'patronymic_female' => 'Анатольевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Илья',
          'patronymic_male' => 'Ильич',
                'patronymic_female' => 'Ильишна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Лариса',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Владислав',
          'patronymic_male' => 'Владиславович',
                'patronymic_female' => 'Владиславовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Лидия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Наталия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Вадим',
          'patronymic_male' => 'Вадимович',
                'patronymic_female' => 'Вадимовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Ксения',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Геннадий',
          'patronymic_male' => 'Генадьевич',
                'patronymic_female' => 'Генадьевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Григорий',
          'patronymic_male' => 'Григорьевич',
                'patronymic_female' => 'Григорьевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Тамара',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Никита',
          'patronymic_male' => 'Никитич',
                'patronymic_female' => 'Никитишна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Алина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Леонид',
          'patronymic_male' => 'Леонидович',
                'patronymic_female' => 'Ленидовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Руслан',
          'patronymic_male' => 'Русланович',
                'patronymic_female' => 'Руслановна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Борис',
          'patronymic_male' => 'Борисович',
                'patronymic_female' => 'Борисовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Кристина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Кирилл',
          'patronymic_male' => 'Кирилович',
                'patronymic_female' => 'Кириловна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Артем',
          'patronymic_male' => 'Артемович',
                'patronymic_female' => 'Артемовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Елизавета',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Инна',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Станислав',
          'patronymic_male' => 'Станиславович',
                'patronymic_female' => 'Станиславовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Валерия',
          'patronymic_male' => 'Валерьевич',
                'patronymic_female' => 'Валерьевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Алла',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Полина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Раиса',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Яна',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Антонина',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Валентин',
          'patronymic_male' => 'Валентинович',
                'patronymic_female' => 'Валентиновна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Федор',
          'patronymic_male' => 'Федорович',
                'patronymic_female' => 'Федоровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Георгий',
          'patronymic_male' => 'Георгиевич',
                'patronymic_female' => 'Георгиевна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Алена',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Егор',
          'patronymic_male' => 'Егорович',
                'patronymic_female' => 'Егоровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Артём',
          'patronymic_male' => 'Артемович',
                'patronymic_female' => 'Артемовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Зинаида',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Олеся',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Степан',
          'patronymic_male' => 'Степанович',
                'patronymic_female' => 'Степановна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Маргарита',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Лилия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Эдуард',
          'patronymic_male' => 'Эдуардович',
                'patronymic_female' => 'Эдуардовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Диана',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Зоя',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Алёна',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Евдокия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Вероника',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Даниил',
          'patronymic_male' => 'Даниилович',
                'patronymic_female' => 'Данииловна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Артур',
          'patronymic_male' => 'Артурович',
                'patronymic_female' => 'Артуровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Пётр',
          'patronymic_male' => 'Петрович',
                'patronymic_female' => 'Петровна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Клавдия',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Ярослав',
          'patronymic_male' => 'Ярославович',
                'patronymic_female' => 'Ярославовна',
          'gender' => 1,       
                'author_id' => 1,
         ],
         [
          'name' => 'Софья',
          'patronymic_male' => null,
                'patronymic_female' => null,
          'gender' => 0,       
                'author_id' => 1,
         ],
         [
          'name' => 'Матвей',
          'patronymic_male' => 'Матвеевич',
                'patronymic_female' => 'Матвеевна',
          'gender' => 1,       
                'author_id' => 1,
         ],

        ]);
    }
}
