<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('products')->insert([
    		[
    			'name' => 'Откатные ворота',
    			'products_category_id' => 2,
    			'company_id' => 1, 
    			'author_id' => 4, 
                'manufacturer_id' => 1,
                'unit_id' => 26,
                'display' => 1,
    		],
            [
                'name' => 'Секционные ворота',
                'products_category_id' => 3,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                'unit_id' => 26, 
                'display' => 1,
            ],
            [
                'name' => 'Забор',
                'products_category_id' => 4,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                'unit_id' => 26, 
                'display' => 1,
            ],

            [
                'name' => 'Труба',
                'products_category_id' => 26,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                'unit_id' => 26, 
                'display' => 1,
            ],

             [
                'name' => 'Прутик',
                'products_category_id' => 26,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                'unit_id' => 26, 
                'display' => 1,
            ],

            [
                'name' => 'Полуфабрик',
                'products_category_id' => 27,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                'unit_id' => 26, 
                'display' => 1,
            ],

            // Шторка
            [
                'name' => 'Блекаут ВЕНЗЕЛЬ розовый',
                'products_category_id' => 11,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут ВЕНЗЕЛЬ терракотовый',
                'products_category_id' => 11,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут БАБОЧКИ',
                'products_category_id' => 12,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут ЛИСТЬЯ',
                'products_category_id' => 12,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут INTERIO',
                'products_category_id' => 11,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут Люстра',
                'products_category_id' => 11,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Дебют Цветы',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард BYRA LUX',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард POINT',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард VALENTINA',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Диана',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Зебра',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Кудри',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард ZARA',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард MOSTAR',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Полоска',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард  Шенил',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Анита',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард 7700',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Жаккард Классика',
                'products_category_id' => 14,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Тафта Вензель',
                'products_category_id' => 15,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Тафта Кружева',
                'products_category_id' => 15,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Канвас однотонный',
                'products_category_id' => 17,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Бархат ADELYA',
                'products_category_id' => 18,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Софт двусторонний',
                'products_category_id' => 19,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен Interio',
                'products_category_id' => 21,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен МИСКЕТ',
                'products_category_id' => 21,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен РОМБ',
                'products_category_id' => 22,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен ЦВЕТЫ',
                'products_category_id' => 23,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен SANPA',
                'products_category_id' => 23,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 6,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен с термопечатью',
                'products_category_id' => 23,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен ЛИСТ Ламелла',
                'products_category_id' => 24,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Лен ПОЛОСКА',
                'products_category_id' => 24,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут однотонный Бирюза',
                'products_category_id' => 13,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
            [
                'name' => 'Блекаут однотонный Болотный',
                'products_category_id' => 13,
                'company_id' => 4, 
                'author_id' => 15, 
                'manufacturer_id' => 5,
                'unit_id' => 4, 
                'display' => 1,
            ],
    	]);
    }
}
