<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('products')->insert([
    		[
    			'name' => 'Откатные ворота',
    			'products_group_id' => 1,
    			'company_id' => 1, 
    			'author_id' => 4, 
                'manufacturer_id' => 1,
                // 'unit_id' => 26,
                'display' => 1,
    		],
            [
                'name' => 'Секционные ворота',
                'products_group_id' => 2,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                // 'unit_id' => 26, 
                'display' => 1,
            ],
            [
                'name' => 'Забор',
                'products_group_id' => 3,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                // 'unit_id' => 26, 
                'display' => 1,
            ],

            [
                'name' => 'C10',
                'products_group_id' => 4,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                // 'unit_id' => 26, 
                'display' => 1,
            ],

             [
                'name' => 'C8',
                'products_group_id' => 4,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                // 'unit_id' => 26, 
                'display' => 1,
            ],

            [
                'name' => 'C12',
                'products_group_id' => 4,
                'company_id' => 1, 
                'author_id' => 4, 
                'manufacturer_id' => null,
                // 'unit_id' => 26, 
                'display' => 1,
            ],

            // Шторка
            // [
            //     'name' => 'Блекаут ВЕНЗЕЛЬ розовый',
            //     'products_group_id' => 11,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут ВЕНЗЕЛЬ терракотовый',
            //     'products_group_id' => 11,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут БАБОЧКИ',
            //     'products_group_id' => 12,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут ЛИСТЬЯ',
            //     'products_group_id' => 12,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут INTERIO',
            //     'products_group_id' => 11,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут Люстра',
            //     'products_group_id' => 11,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Дебют Цветы',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард BYRA LUX',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард POINT',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард VALENTINA',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Диана',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Зебра',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Кудри',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард ZARA',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард MOSTAR',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Полоска',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард  Шенил',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Анита',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард 7700',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Жаккард Классика',
            //     'products_group_id' => 14,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Тафта Вензель',
            //     'products_group_id' => 15,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Тафта Кружева',
            //     'products_group_id' => 15,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Канвас однотонный',
            //     'products_group_id' => 17,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Бархат ADELYA',
            //     'products_group_id' => 18,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Софт двусторонний',
            //     'products_group_id' => 19,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен Interio',
            //     'products_group_id' => 21,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен МИСКЕТ',
            //     'products_group_id' => 21,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен РОМБ',
            //     'products_group_id' => 22,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен ЦВЕТЫ',
            //     'products_group_id' => 23,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен SANPA',
            //     'products_group_id' => 23,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 6,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен с термопечатью',
            //     'products_group_id' => 23,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен ЛИСТ Ламелла',
            //     'products_group_id' => 24,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Лен ПОЛОСКА',
            //     'products_group_id' => 24,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут однотонный Бирюза',
            //     'products_group_id' => 13,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
            // [
            //     'name' => 'Блекаут однотонный Болотный',
            //     'products_group_id' => 13,
            //     'company_id' => 4, 
            //     'author_id' => 15, 
            //     'manufacturer_id' => 5,
            //     // 'unit_id' => 18,
            //     'display' => 1,
            // ],
    	]);
    }
}
