<?php

use Illuminate\Database\Seeder;

class UnitsTableSeeder extends Seeder
{

	public function run()
	{
		DB::table('units')->insert([
			// Длина
			[
				'name' => 'Миллиметр', 
				'abbreviation' => 'мм', 
				'ratio' => 0.001,
				'units_category_id' => 1,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Сантиметр', 
				'abbreviation' => 'см', 
				'ratio' => 0.01, 
				'units_category_id' => 1,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Дециметр', 
				'abbreviation' => 'дм', 
				'ratio' => 0.1,
				'units_category_id' => 1, 
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Метр', 
				'abbreviation' => 'м', 
				'ratio' => 1, 
				'units_category_id' => 1,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Километр', 
				'abbreviation' => 'км', 
				'ratio' => 1000, 
				'units_category_id' => 1,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],

			// Масса
			[
				'name' => 'Миллиграмм', 
				'abbreviation' => 'мг', 
				'ratio' => 0.000001, 
				'units_category_id' => 2,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Грамм', 
				'abbreviation' => 'г', 
				'ratio' => 0.001, 
				'units_category_id' => 2,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Килограмм', 
				'abbreviation' => 'кг', 
				'ratio' => 1, 
				'units_category_id' => 2,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Центнер', 
				'abbreviation' => 'ц', 
				'ratio' => 100, 
				'units_category_id' => 2,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Тонна', 
				'abbreviation' => 'т', 
				'ratio' => 1000, 
				'units_category_id' => 2,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],

			// Время
			[
				'name' => 'Милисекунда', 
				'abbreviation' => 'мс', 
				'ratio' => 0.001, 
				'units_category_id' => 3,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Секунда', 
				'abbreviation' => 'с', 
				'ratio' => 1, 
				'units_category_id' => 3,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Минута', 
				'abbreviation' => 'мин', 
				'ratio' => 60, 
				'units_category_id' => 3,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Час', 
				'abbreviation' => 'ч', 
				'ratio' => 3600, 
				'units_category_id' => 3,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],

			// Площадь
			[
				'name' => 'Квадратный миллиметр', 
				'abbreviation' => 'кв. мм', 
				'ratio' => 0.001, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Квадратный сантиметр', 
				'abbreviation' => 'кв. см', 
				'ratio' => 0.01, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Квадратный дециметр', 
				'abbreviation' => 'кв. дм', 
				'ratio' => 0.1, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Квадратный метр', 
				'abbreviation' => 'кв. м', 
				'ratio' => 1, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Квадратный километр', 
				'abbreviation' => 'кв. км', 
				'ratio' => 1000, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Гектар', 
				'abbreviation' => 'га', 
				'ratio' => 10000, 
				'units_category_id' => 4,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],

			// Обьем
			// [
			// 	'name' => 'Кубический миллиметр', 
			// 	'abbreviation' => 'куб. см', 
			// 	'ratio' => 0.001, 
			// 	'units_category_id' => 5,
			// 	'system_item' => 1, 
			// 	'author_id' => 1, 
			// 	'moderation' => null, 
			// ],
			[
				'name' => 'Кубический сантиметр', 
				'abbreviation' => 'куб. см', 
				'ratio' => 0.000001, 
				'units_category_id' => 5,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Миллилитр', 
				'abbreviation' => 'мл', 
				'ratio' => 0.000001, 
				'units_category_id' => 5,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Кубический дециметр', 
				'abbreviation' => 'куб. дм', 
				'ratio' => 0.001, 
				'units_category_id' => 5,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Литр', 
				'abbreviation' => 'л', 
				'ratio' => 0.001, 
				'units_category_id' => 5,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Кубический метр', 
				'abbreviation' => 'куб. м', 
				'ratio' => 1, 
				'units_category_id' => 5,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],

			// Количество
			[
				'name' => 'Штука', 
				'abbreviation' => 'шт', 
				'ratio' => 1, 
				'units_category_id' => 6,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],
			[
				'name' => 'Пара', 
				'abbreviation' => 'пара', 
				'ratio' => 2, 
				'units_category_id' => 6,
				'system_item' => 1, 
				'author_id' => 1, 
				'moderation' => null, 
			],


		]);
	}
}
