<?php

use Illuminate\Database\Seeder;

class MenusTestTableSeeder extends Seeder
{
  /**
  * Run the database seeds.
  *
  * @return void
  */
  public function run()
  {
    DB::table('menus')->insert([
    [
        'name' => 'О компании',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 43,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 1,
    ],
    [
        'name' => 'Новости',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 44,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 2,
    ],
    [
        'name' => 'Контакты',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 45,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 6,
    ],
    [
        'name' => 'Замер',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 46,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 5,
    ],
    [
        'name' => 'Гаражные ворота',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 47,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 1,
    ],
    [
        'name' => 'Уличные ворота',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 48,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 2,
    ],
    [
        'name' => 'Рольставни',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 49,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 5,
    ],
    [
        'name' => 'Автоматика',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 50,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 6,
    ],
    [
        'name' => 'Стальные двери',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 51,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => null,
        'sort' => 8,
    ],
    [
        'name' => 'Перегрузочные системы',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 52,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 10,
    ],
    [
        'name' => 'Сервисный центр',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 53,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 3,
    ],
    [
        'name' => 'База знаний',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 54,
        'navigation_id' => 3,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 4,
    ],
    [
        'name' => 'Заборы',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 55,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 3,
    ],
    [
        'name' => 'Ангары',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 56,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => null,
        'sort' => 4,
    ],
    [
        'name' => 'Шлагбаумы',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 57,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 7,
    ],
    [
        'name' => 'Противопожарные ворота',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 58,
        'navigation_id' => 4,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => 9,
    ],
    [
        'name' => 'Подать заявку на замер',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 46,
        'navigation_id' => 5,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
    [
        'name' => 'Наша команда',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 59,
        'navigation_id' => 5,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => null,
        'sort' => null,
    ],
    [
        'name' => 'Вакансии',
        'icon' => null,
        'alias' => null,
        'parent_id' => null,
        'page_id' => 60,
        'navigation_id' => 5,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => null,
        'sort' => null,
    ],
    [
        'name' => 'Instagram',
        'icon' => null,
        'alias' => 'https://instagram.com/vorotamars',
        'parent_id' => null,
        'page_id' => null,
        'navigation_id' => 6,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
    [
        'name' => 'Facebook',
        'icon' => null,
        'alias' => 'https://www.facebook.com/vorotamars',
        'parent_id' => null,
        'page_id' => null,
        'navigation_id' => 6,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
    [
        'name' => 'Вконтакте',
        'icon' => null,
        'alias' => 'https://vk.com/vorotamars',
        'parent_id' => null,
        'page_id' => null,
        'navigation_id' => 6,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
    [
        'name' => 'Одноклассники',
        'icon' => null,
        'alias' => 'https://ok.ru/vorotamars',
        'parent_id' => null,
        'page_id' => null,
        'navigation_id' => 6,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
    [
        'name' => 'Youtube',
        'icon' => null,
        'alias' => 'https://youtube.com/channel/UCTVWvgfC2wT-Po1HfFk',
        'parent_id' => null,
        'page_id' => null,
        'navigation_id' => 6,
        'company_id' => 1,
        'system_item' => null,
        'author_id' => 1,
        'display' => 1,
        'sort' => null,
    ],
   

]);
}
}
