<?php

use Illuminate\Database\Seeder;

class PagesTestTableSeeder extends Seeder
{

    public function run()
    {
        // Создаем страницы для crm системы
        DB::table('pages')->insert([

            [
                'name' => 'Главная',
                'site_id' => 2,
                'title' => 'Воротная компания "Марс"',
                'description' => 'Производство и профессиональный монтаж уличных и гаражных ворот от компании МАРС. Купить секционные или откатные ворота - просто как никогда!',
                'alias' => 'company',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Новости',
                'site_id' => 2,
                'title' => 'Новости',
                'description' => 'Новости, акции и готовые решения от воротной компании Марс. Телефон в Иркутске: 8 (3952) 71-77-75',
                'alias' => 'news',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Контакты',
                'site_id' => 2,
                'title' => 'Контакты',
                'description' => 'Контактные данные воротной компании Марс. Телефон в Иркутске: 8 (3952) 71-77-75',
                'alias' => 'contacts',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Замер',
                'site_id' => 2,
                'title' => 'Замер',
                'description' => 'Закажите бесплатный замер на приобретение уличных или гаражных ворот. Телефон в Иркутске: 8 (3952) 71-77-75',
                'alias' => 'measurement',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Гаражные ворота',
                'site_id' => 2,
                'title' => 'Гаражные ворота',
                'description' => 'Секционные гаражные ворота от Doorhan (Дорхан) в Иркутске. Купить автоматические подъемные ворота - быстро и без хлопот!',
                'alias' => 'garage_gates',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Уличные ворота',
                'site_id' => 2,
                'title' => 'Уличные ворота',
                'description' => 'Купить автоматические откатные ворота высокого качества - быстро и без хлопот: описание конструктива, выбор материалов, варианты дизайна',
                'alias' => 'street_gates',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Рольставни',
                'site_id' => 2,
                'title' => 'Рольставни',
                'description' => 'Продажа и монтаж рольворот и рольставень от производителя (Doorhan) в Иркутске. Высокое качество.',
                'alias' => 'rollets',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Автоматика',
                'site_id' => 2,
                'title' => 'Автоматика',
                'description' => 'Автоматика Doorhan: электроприводы для секционных, сдвижных, распашных ворот. Вы можете купить сейчас или заказать приводы Shaft, Sectional, Sliding, Swing, Arm и другие.',
                'alias' => 'automatics',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Стальные двери',
                'site_id' => 2,
                'title' => 'Стальные двери',
                'description' => 'Поставка и монтаж стальных дверей от Doorhan в Иркутске и Иркутской области.',
                'alias' => 'steel_doors',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => null,
            ],
            [
                'name' => 'Перегрузочные системы',
                'site_id' => 2,
                'title' => 'Перегрузочные системы',
                'description' => 'Перегрузочные системы от Doorhan: механические и электрогидравлические платформы.',
                'alias' => 'handling_systems',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Сервисный центр',
                'site_id' => 2,
                'title' => 'Сервисный центр',
                'description' => 'Сервисный центр Doorhan (Дорхан) в Иркутске. Ремонт автоматики - быстро и без хлопот!',
                'alias' => 'service_center',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'База знаний',
                'site_id' => 2,
                'title' => 'База знаний',
                'description' => 'Профессиональная команда воротной компании Марс: безупречное производство и качественный монтаж гаражных и уличных ворот',
                'alias' => 'knowledge',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Заборы',
                'site_id' => 2,
                'title' => 'Заборы',
                'description' => 'Купить автоматические откатные ворота высокого качества - быстро и без хлопот: описание конструктива, выбор материалов, варианты дизайна',
                'alias' => 'fences',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Ангары',
                'site_id' => 2,
                'title' => 'Ангары',
                'description' => 'Купить ангар в Иркутске, Ангарске. Модульные конструкции любого размера и для любых нужд',
                'alias' => 'hangars',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => null,
            ],
            [
                'name' => 'Шлагбаумы',
                'site_id' => 2,
                'title' => 'Шлагбаумы',
                'description' => 'Автоматика Doorhan: электроприводы для секционных, сдвижных, распашных ворот. Вы можете купить сейчас или заказать приводы Shaft, Sectional, Sliding, Swing, Arm и другие.',
                'alias' => 'barriers',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Противопожарные ворота',
                'site_id' => 2,
                'title' => 'Противопожарные ворота',
                'description' => 'Противопожарные ворота от Doorhan.',
                'alias' => 'fire_gates',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Команда',
                'site_id' => 2,
                'title' => 'Команда',
                'description' => 'Профессиональная команда воротной компании Марс: безупречное производство и качественный монтаж гаражных и уличных ворот',
                'alias' => 'team',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],
            [
                'name' => 'Вакансии',
                'site_id' => 2,
                'title' => 'Вакансии',
                'description' => 'Профессиональная команда воротной компании Марс: безупречное производство и качественный монтаж гаражных и уличных ворот',
                'alias' => 'vacancies',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],

            [
                'name' => 'Комплектация для откатных ворот',
                'site_id' => 2,
                'title' => 'Комплектация для откатных ворот',
                'description' => 'Готовая комплектация откатных уличных ворот для тех, кто решил их сделать своими руками: автоматика, балки, роликовые опоры, ловители, удерживающие устройства и многое другое.',
                'alias' => 'street_gate_set',
                'company_id' => 1,
                'system_item' => null,
                'author_id' => 7,
                'display' => 1,
            ],

        ]);
}
}
