<?php

use Illuminate\Database\Seeder;

class UsersTestTableSeeder extends Seeder
{

    public function run()
    {

    	DB::table('users')->insert([
            [
                'login' => 'timoshenko', 
                'email' => 'sidorov@mail.ru', 
                'password' => bcrypt('123456'), 
                'nickname' => 'timoshenko', 
                'first_name' => 'Алексей',
                'second_name' => 'Тимошенко',
                'phone' => 89024673334, 
                'location_id' => 5,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 1,
                'god' => null, 
                'system' => false,
                'author_id' => 1, 
                'moderation' => false,
                'sex' => 1, 
            ],
            [
                'login' => 'mironov', 
                'email' => 'mironov@mail.ru', 
                'password' => bcrypt('123456'), 
                'nickname' => 'mironov', 
                'first_name' => 'Юрий',
                'second_name' => 'Миронов',
                'phone' => 89024112734, 
                'location_id' => 6,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 1,
                'god' => null, 
                'system' => false,
                'author_id' => 4, 
                'moderation' => false,
                'sex' => 1, 
            ],
            [
                'login' => 'kondrachuk', 
                'email' => 'kondrachuk@mail.ru', 
                'password' => bcrypt('123456'), 
                'nickname' => 'kondrachuk', 
                'first_name' => 'Анна',
                'second_name' => 'Кондрачук',
                'phone' => 86784672734, 
                'location_id' => 7,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 1,
                'god' => null, 
                'system' => false,
                'author_id' => 4, 
                'moderation' => false,
                'sex' => 0, 
            ],
            [
                'login' => 'davydenko', 
                'email' => 'd@vorotamars.ru', 
                'password' => bcrypt('123456'), 
                'first_name' => 'Максим',
                'second_name' => 'Давыденко',
                'nickname' => 'davydenko', 
                'phone' => 89025687585, 
                'location_id' => 8,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 1,
                'god' => null, 
                'system' => false,
                'author_id' => 4, 
                'moderation' => false,
                'sex' => 1, 
            ],
            [
                'login' => 'ylan1', 
                'email' => 'ylan1@vorotamars.ru', 
                'password' => bcrypt('123456'), 
                'first_name' => 'Улан',
                'second_name' => 'Первый',
                'nickname' => 'ylan1', 
                'phone' => 81111111111, 
                'location_id' => 2,
                'user_type' => 9, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 2,
                'god' => null, 
                'system' => false,
                'author_id' => 4, 
                'moderation' => false,
                'sex' => 1, 
            ],
            [
                'login' => 'ylan2', 
                'email' => 'ylan2@vorotamars.ru', 
                'password' => bcrypt('123456'), 
                'first_name' => 'Улан',
                'second_name' => 'Второй',
                'nickname' => 'ylan2', 
                'phone' => 81111111112, 
                'location_id' => 10,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 2,
                'god' => null, 
                'system' => false,
                'author_id' => 8, 
                'moderation' => false,
                'sex' => 1, 
            ],
            [
                'login' => 'ylan3', 
                'email' => 'ylan3@vorotamars.ru', 
                'password' => bcrypt('123456'), 
                'first_name' => 'Улан',
                'second_name' => 'Третий',
                'nickname' => 'ylan3', 
                'phone' => 81111111113, 
                'location_id' => 11,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 2,
                'god' => null, 
                'system' => false,
                'author_id' => 8, 
                'moderation' => false,
                'sex' => 0, 
            ],
            [
                'login' => 'butin', 
                'email' => 'butin@mail.ru', 
                'password' => bcrypt('123456'), 
                'nickname' => 'butin', 
                'first_name' => 'Николай',
                'second_name' => 'Бутин',
                'phone' => 89024673399, 
                'location_id' => 12,
                'user_type' => 1, 
                'access_block' => 0, 
                'company_id' => 1, 
                'filial_id' => 1,
                'god' => null, 
                'system' => false,
                'author_id' => 1, 
                'moderation' => false,
                'sex' => 1, 
            ],
        ]);
    }
}
